name: Continious Integration 

on:
  push:
    branches: [ master ]


jobs:
  run_tests:
    runs-on: ubantu-latest 
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]


    steps:
    - uses: actions/checkout@v2
    # install python
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version:${{ matrix.python-version }}

    # install python dependencies
    -name: Install dependencies
     run: |
       python -m pip install --upgrage pip
       pip install -r requirements.txt;

    # run actual unit tests
    - name: Test with unittest
      run: |
        python -m unittest
